version: '3.8'

services:
  app:
    build:
      context: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testpro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Manel@2024#
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Manel@2024#   # Utilisez cette variable pour configurer le mot de passe root
      MYSQL_DATABASE: testpro
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
